# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tertúlia Matinal em Podcast
email: rodrigo+tertuliamatinal@familianascimento.org
description: "Uma versão em podcast das tertúlias matinais do canal do Tertuliarium no Youtube, somente para meu consumo próprio. Todos os diretos são do CEAEC. Nas Tertúlias Matinais são discutidos diversos assuntos da conscienciologia."
subtitle: ""
lang: en-us
author: Welton Rodrigo
copyright: "&#xA9; 2015"
baseurl: "/tertuliamatinal" # the subpath of your site, e.g. /blog
url: "https://weltonrodrigo.github.io/" # the base hostname & protocol for your site

collections:
  category:
    output: true

permalink: /:year/:title.html

#Timezone
timezone: America/Sao_Paulo

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

